### ISSUE TITLE
Windows: env var `$FORTUNE_FILE` not found by default

### ISSUE THREAD

**Issue by pabloqpacin** [bmc/fortune#7]
I installed the program via `pip` and downloaded your [fortune cookies](https://github.com/bmc/fortunes).
Now I can easily run `fortune path/to/file` and even `fortune $FORTUNE_FILE` as displayed on the screenshot. However, a good simple `fortune` fails to find the variable.

This is how I set the variable on my  $PROFILE, if it helps:
```powershell
$FORTUNE_FILE = Get-ChildItem -Path "$env:HOMEPATH\dotfiles\docs\fortunes" | Get-Random | Select-Object -ExpandProperty FullName
```

It's great as it is, but maybe could you describe how to properly set up the environment variable on Windows? Thanks!!

<br>

![image](https://github.com/bmc/fortune/assets/110383181/ae5539ac-1a0b-4474-baee-31b21bbd1208)

**Comment by bmc** [comment]
Honestly, I don't use Windows, except for gaming. I don't test any of my stuff on Windows; I routinely use my stuff, including `fortune`, on Unix and MacOS systems.

That said, perhaps this article might help: https://www.computerhope.com/issues/ch000549.htm 

That's consistent with my recollection of how one sets environment variables on Windows.

**Comment by pabloqpacin** [comment]
Alright, thank you sir.
